# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rocket-io}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Tomer"]
  s.date = %q{2011-08-25}
  s.default_executable = %q{rocket}
  s.description = %q{Realtime web applicatioin framework that uses Web Sockets for (nearly) everything}
  s.email = %q{michaeltomer@gmail.com}
  s.executables = ["rocket"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/rocket",
    "lib/lib/rocket.rb",
    "lib/lib/rocket/bolt.rb",
    "lib/lib/rocket/controller.rb",
    "lib/lib/rocket/initializer.rb",
    "lib/lib/rocket/monkey_patches.rb",
    "lib/lib/rocket/rocket_user.rb",
    "lib/lib/rocket/runner.rb",
    "lib/public/html/main.html",
    "lib/public/javascripts/formtacular.js",
    "lib/public/javascripts/jade.js",
    "lib/public/javascripts/jquery.js",
    "lib/public/javascripts/rocket.js",
    "lib/public/javascripts/rocket_utils.js",
    "lib/rocket-io.rb",
    "lib/vendor/.gitignore",
    "lib/vendor/em-redis-0.3.0/History.txt",
    "lib/vendor/em-redis-0.3.0/lib/em-redis.rb",
    "lib/vendor/em-redis-0.3.0/lib/em-redis/redis_protocol.rb",
    "lib/vendor/em-redis-0.3.0/lib/em-redis/version.rb",
    "lib/vendor/em-synchrony/Gemfile",
    "lib/vendor/em-synchrony/README.md",
    "lib/vendor/em-synchrony/Rakefile",
    "lib/vendor/em-synchrony/em-synchrony.gemspec",
    "lib/vendor/em-synchrony/examples/all.rb",
    "lib/vendor/em-synchrony/examples/bitly.rb",
    "lib/vendor/em-synchrony/examples/go/README.md",
    "lib/vendor/em-synchrony/examples/go/channel.go",
    "lib/vendor/em-synchrony/examples/go/channel.rb",
    "lib/vendor/em-synchrony/examples/go/consumer-publisher.go",
    "lib/vendor/em-synchrony/examples/go/consumer-publisher.rb",
    "lib/vendor/em-synchrony/examples/go/go.rb",
    "lib/vendor/em-synchrony/examples/nethttp.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/connection_pool.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-bitly.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-http.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-jack.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-memcache.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-mongo.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-multi.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-mysqlplus.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-redis.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/em-remcached.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/iterator.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/mongo.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/mongoid.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/tcpsocket.rb",
    "lib/vendor/em-synchrony/lib/em-synchrony/thread.rb",
    "lib/vendor/em-synchrony/spec/beanstalk_spec.rb",
    "lib/vendor/em-synchrony/spec/connection_pool_spec.rb",
    "lib/vendor/em-synchrony/spec/em-mongo_spec.rb",
    "lib/vendor/em-synchrony/spec/helper/all.rb",
    "lib/vendor/em-synchrony/spec/helper/stub-http-server.rb",
    "lib/vendor/em-synchrony/spec/helper/tolerance_matcher.rb",
    "lib/vendor/em-synchrony/spec/http_spec.rb",
    "lib/vendor/em-synchrony/spec/inlinesync_spec.rb",
    "lib/vendor/em-synchrony/spec/iterator_spec.rb",
    "lib/vendor/em-synchrony/spec/memcache_spec.rb",
    "lib/vendor/em-synchrony/spec/mongo_spec.rb",
    "lib/vendor/em-synchrony/spec/mysqlplus_spec.rb",
    "lib/vendor/em-synchrony/spec/redis_spec.rb",
    "lib/vendor/em-synchrony/spec/remcached_spec.rb",
    "lib/vendor/em-synchrony/spec/tcpsocket_spec.rb",
    "rocket-io.gemspec",
    "test/helper.rb",
    "test/test_rocket-io.rb"
  ]
  s.homepage = %q{http://github.com/actsasbuffoon/rocket-io}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Realtime web application framework}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.1.7"])
      s.add_runtime_dependency(%q<thin>, [">= 1.2.11"])
      s.add_runtime_dependency(%q<async_sinatra>, [">= 0.5.0"])
      s.add_runtime_dependency(%q<em-websocket>, [">= 0.3.1"])
      s.add_runtime_dependency(%q<json>, [">= 1.5.1"])
      s.add_runtime_dependency(%q<therubyracer>, [">= 0.9.3"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_runtime_dependency(%q<slop>, [">= 0"])
      s.add_runtime_dependency(%q<rocco>, [">= 0"])
      s.add_runtime_dependency(%q<pygmentize>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.1.7"])
      s.add_dependency(%q<thin>, [">= 1.2.11"])
      s.add_dependency(%q<async_sinatra>, [">= 0.5.0"])
      s.add_dependency(%q<em-websocket>, [">= 0.3.1"])
      s.add_dependency(%q<json>, [">= 1.5.1"])
      s.add_dependency(%q<therubyracer>, [">= 0.9.3"])
      s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
      s.add_dependency(%q<slop>, [">= 0"])
      s.add_dependency(%q<rocco>, [">= 0"])
      s.add_dependency(%q<pygmentize>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.1.7"])
    s.add_dependency(%q<thin>, [">= 1.2.11"])
    s.add_dependency(%q<async_sinatra>, [">= 0.5.0"])
    s.add_dependency(%q<em-websocket>, [">= 0.3.1"])
    s.add_dependency(%q<json>, [">= 1.5.1"])
    s.add_dependency(%q<therubyracer>, [">= 0.9.3"])
    s.add_dependency(%q<nokogiri>, [">= 1.4.4"])
    s.add_dependency(%q<slop>, [">= 0"])
    s.add_dependency(%q<rocco>, [">= 0"])
    s.add_dependency(%q<pygmentize>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

